CREATE TABLE Users (
  UserID NUMBER PRIMARY KEY,
  Username VARCHAR2(50) UNIQUE NOT NULL,
  PasswordHash VARCHAR2(255) NOT NULL,
  FullName VARCHAR2(100) NOT NULL,
  Role VARCHAR2(20) NOT NULL
);

CREATE TABLE Students (
  StudentID NUMBER PRIMARY KEY,
  StudentCode VARCHAR2(20) UNIQUE NOT NULL,
  Name VARCHAR2(100) NOT NULL,
  Email VARCHAR2(120) NOT NULL,
  Phone VARCHAR2(30) NOT NULL,
  Department VARCHAR2(50) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE Rooms (
  RoomID NUMBER PRIMARY KEY,
  RoomNumber VARCHAR2(20) UNIQUE NOT NULL,
  Capacity NUMBER NOT NULL,
  RoomType VARCHAR2(20) NOT NULL
);

CREATE TABLE RoomAllocation (
  AllocationID NUMBER PRIMARY KEY,
  StudentID NUMBER NOT NULL,
  RoomID NUMBER NOT NULL,
  AllocationDate TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_alloc_student FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
  CONSTRAINT fk_alloc_room FOREIGN KEY (RoomID) REFERENCES Rooms(RoomID)
);

CREATE TABLE Payments (
  PaymentID NUMBER PRIMARY KEY,
  StudentID NUMBER NOT NULL,
  Amount NUMBER(10,2) NOT NULL,
  PaymentDate DATE NOT NULL,
  Status VARCHAR2(20) NOT NULL,
  Note VARCHAR2(200),
  CONSTRAINT fk_payment_student FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);

CREATE TABLE Complaints (
  ComplaintID NUMBER PRIMARY KEY,
  StudentID NUMBER NOT NULL,
  Description VARCHAR2(500) NOT NULL,
  Status VARCHAR2(20) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_complaint_student FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);

CREATE TABLE Visitors (
  VisitorID NUMBER PRIMARY KEY,
  StudentID NUMBER NOT NULL,
  VisitorName VARCHAR2(100) NOT NULL,
  EntryTime TIMESTAMP NOT NULL,
  ExitTime TIMESTAMP,
  CONSTRAINT fk_visitor_student FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);

CREATE SEQUENCE Users_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Students_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Rooms_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RoomAllocation_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Payments_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Complaints_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Visitors_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER Users_bi
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
  IF :NEW.UserID IS NULL THEN
    SELECT Users_seq.NEXTVAL INTO :NEW.UserID FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER Students_bi
BEFORE INSERT ON Students
FOR EACH ROW
BEGIN
  IF :NEW.StudentID IS NULL THEN
    SELECT Students_seq.NEXTVAL INTO :NEW.StudentID FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER Rooms_bi
BEFORE INSERT ON Rooms
FOR EACH ROW
BEGIN
  IF :NEW.RoomID IS NULL THEN
    SELECT Rooms_seq.NEXTVAL INTO :NEW.RoomID FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER RoomAllocation_bi
BEFORE INSERT ON RoomAllocation
FOR EACH ROW
BEGIN
  IF :NEW.AllocationID IS NULL THEN
    SELECT RoomAllocation_seq.NEXTVAL INTO :NEW.AllocationID FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER Payments_bi
BEFORE INSERT ON Payments
FOR EACH ROW
BEGIN
  IF :NEW.PaymentID IS NULL THEN
    SELECT Payments_seq.NEXTVAL INTO :NEW.PaymentID FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER Complaints_bi
BEFORE INSERT ON Complaints
FOR EACH ROW
BEGIN
  IF :NEW.ComplaintID IS NULL THEN
    SELECT Complaints_seq.NEXTVAL INTO :NEW.ComplaintID FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER Visitors_bi
BEFORE INSERT ON Visitors
FOR EACH ROW
BEGIN
  IF :NEW.VisitorID IS NULL THEN
    SELECT Visitors_seq.NEXTVAL INTO :NEW.VisitorID FROM dual;
  END IF;
END;
/

CREATE INDEX idx_students_department ON Students(Department);
CREATE INDEX idx_payments_student ON Payments(StudentID);
CREATE INDEX idx_allocations_room ON RoomAllocation(RoomID);
